# site settings
title: Playground for Jaewoo
description: > # this means to ignore newlines until "baseurl:"
  This is a blog and a personal page for Jaewoo Park. I'm a developer
  with background in machine learning, biomedical engineering, software
  engineering, cloud infrastructures, computer vision, deep learning,
  sensor fusion, and self driving cars.
permalink: ':title/'
url: "http://jaewoopark.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Jaewoo Park # add your name
author-img: placeholder.jpg # add your photo
about-author: I am a developer/engineer with interests in data science, full stack development, and healthcare. # add description
twitter: jwupark # add your Twitter handle
github: aselius # add your Github handle
linkedin: jaewoopark91 # add your Linkedin handle
email: jaewoopark91@gmail.com # add your Email address

# Disqus
discus-identifier: jaewoopark91 # add your discus identifier

# Tracker
analytics: UA-108429238-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
